module.exports = [
  { path: "/users", route: require("./userRoutes") },
  { path: "/jobtitle", route: require("./jobTitleRoutes") },
  { path: "/department", route: require("./departmentRoutes") },
  { path: "/role", route: require("./roleRoutes") },
  { path: "/auth", route: require("./authRoutes") },
  { path: "/da-reason", route: require("./disciplinaryActionReasonRoutes") },
  {
    path: "/warning-level",
    route: require("./disciplinaryActionWarningLevelRoutes"),
  },
  { path: "/incident-types", route: require("./incidentTypeRoutes") },
  { path: "/type-feedback", route: require("./typeFeedbackRoutes") },
  { path: "/feedback", route: require("./feedbackRoutes") },
  { path: "/incident", route: require("./incidentRoutes") },
  { path: "/da", route: require("./disciplinaryActionRoutes") },
  { path: "/job-title-change", route: require("./jobTitleChangeRoutes") },
  { path: "/department-change", route: require("./departmentChangeRoutes") },
  { path: "/job-title-dept", route: require("./jobTitleDepartmentRoutes") },
  { path: "/job-title-roles", route: require("./jobTitleRoleRoutes") },
  { path: "/user-roles", route: require("./userRoleRoutes") },
  { path: "/role-permissions", route: require("./rolePermissionRoutes") },
  { path: "/permissions", route: require("./permissionRoutes") },
  { path: "/da-tasks", route: require("./disciplinaryActionTaskRoutes") },
  { path: "/comment-feedback", route: require("./commentFeedbackRoutes") },
  { path: "/eval-saved", route: require("./evaluationSavedRoutes") },
  { path: "/eval-type", route: require("./evaluationTypeRoutes") },
  { path: "/eval-params", route: require("./evaluationParameterRoutes") },
  {
    path: "/eval-params-weight",
    route: require("./EvaluationParameterWeightRoutes"),
  },
  {
    path: "/eval-calification",
    route: require("./evaluationCalificationRoutes"),
  },
  { path: "/eval-master", route: require("./evaluationMasterRoutes") },
  { path: "/eval-detail", route: require("./evaluationDetailRoutes") },
  { path: "/action-plan", route: require("./actionPlanRoutes") },
  { path: "/action-plan-task", route: require("./actionPlanTaskRoutes") },
  { path: "/action-plan-param", route: require("./actionPlanParameterRoutes") },
  {
    path: "/permission-category",
    route: require("./permissionCategoryRoutes"),
  },
  { path: "/change-reason", route: require("./changeReasonRoutes") },
  { path: "/user-hierarchy", route: require("./userHierarchyRoutes") },
  { path: "/job-level", route: require("./jobLevelRoutes") },
  { path: "/job-title-level", route: require("./jobTitleLevelRoutes") },
  { path: "/user-preference", route: require("./userPreferencesRoutes") },
  { path: "/summary", route: require("./summaryRoutes") },
  { path: "/eval360", route: require("./evaluation360Routes") },
  { path: "/files", route: require("./fileUploadRoutes") },
  { path: "/logs", route: require("./logRoutes") },
  { path: "/notifications", route: require("./notificationRoutes") },
];
